- Lang/Dart/hello-world.dart
- Lang/Dart/installation.md
Hello world for dart is added !! Installation.md will be edited soon.
> [Dart] - hello world added!

- Lang/CoffeeScript/Installation.md
- Lang/CoffeeScript/hello-world.coffee
- Lang/Nim/hello-world.nim
- Lang/Nim/installation.md
- Lang/TypeScript/hello-world.ts
- Lang/TypeScript/installation.md
> Nim language

- Lang/julia/helloworld.jl
> Priyanka julia

- Lang/CoffeeScript/workspace.code-workspace
- Lang/Haskell/hello-world.hs
- Lang/Haskell/installation.md
Submitting hello world code for haskell language
> Adding haskell hello-world code file

- Lang/F#/hello-world.fsx
- Lang/F#/installaion.md
> Hemanth F#

- .github/pull_request_template.md
Created pull_request_template file.
> Adding pull_request_template.md file

- CONTRIBUTING.md
Adding `CONTRIBUTING.md`
This PR fixes #NA
**Notes for Reviewers**
Ready to merge! :slightly_smiling_face: 
> CONTRIBUTING.md Added

- Lang/PYTHON/installation.md
Added installation  Python.
This PR fixes #
Yes
> Added installation python

- README.md
Things added/changed:
- Add a detailed readme.
- Closes #38.
> feat: Add a detailed readme

- package-lock.json
- package.json
I strictly locked the Node.js version to v14 due to deployment limitations of Vercel.
> 🛠 hard pinned to Node.js v14 (LTS)

- LICENSE.md
- README.md
> 📚 added some bling to the README.md

- lang/java.md
> adding java language

- lang/C.md
Signed-off-by: Ritvik Shukla <ritvikshukla261@gmail.com>
> adding C language

- lang/python.md
Lang added : python
This PR fixes # NA
Ready to review!
**Discord id** (eg: DEVSTRONS'#0238):  aaquib ali#3729
> adding python language

- lang/dart.md
This PR fixes #
**Discord id** (eg: DEVSTRONS'#0238): Chandan#0862
> adding dart language

- lang/dart.md
- Fix Markdown linter issues in `lang/dart.md` introduced in #56.
Ready to merge.
**Discord id** (eg: DEVSTRONS'#0238):
Panquesito7#3723
> Fix Markdown linter issues in `lang/dart.md`

- CODE_OF_CONDUCT.md
Code of Conduct added (minimal with open source project)
The Code of Conduct just going to shoot, initialize the requirement of contributors to get hands dirty. Also, it's an in-built used for Open source projects minimally. 
This PR fixes #N.A.
Code of Conduct is very essential for open source project, if need to add more points, pl review & take your step forward for contributing!
**Discord ID** (e.g.: DEVSTRONS'#0238): aminos  🇮🇳#2567
> 📜 Code of Conduct - Support

- lang/dart.md
- Fix minor spelling typo.
Ready to merge.
Panquesito7#3723
> fix: minor spelling typo

- src/sections/header/index.html
Added link to navigation 
This PR fixes #70 
- [✔] Yes, I am a Member of **DEVSTRONS'**
! Raj#1813
> Added Link to discord

- lang/Julia.md
Added the Julia language to the list.
This PR fixes #83 
**Discord ID** - **Shivansh Yadav#6952**
> Adding Julia language

- lang/go.md
Adds golang
This PR fixes #74 
Bug fixed successfully, Ready to merge 🙂 
**Discord ID** Krish Gupta#6241
> feat(lang): add golang

- README.md
- package-lock.json
- package.json
- server/routes/list.js
- server/routes/serve.js
- src/assets/scripts/core/api.js
- src/assets/scripts/core/parse.js
- Conversion of markdown files into HTML.
- Fetching of files from lang folder.
This PR fixes # NA
**[Signed commits](https://github.com/devstrons/hello-world/blob/master/CONTRIBUTING.md)**
! Eren#8627
> revamp: Enhancement & Fixing bugs

- lang/haskell.md
I have added Haskell language in the `lang` folder.
This PR fixes #97 
I have tried my best to make this contribution useful, you can review it let me know if any changes are required. 
**[Signed commits](https://github.com/devstrons/hello-world/blob/master/CONTRIBUTING.md)**
**Discord ID** Rio_#5346
> Add Haskell Language

- src/assets/styles/_nprogress.css
- src/sections/header/index.html
- src/sections/main/index.css
This PR fixes #
**[Signed commits](https://github.com/devstrons/heloworld/blob/master/CONTRIBUTING.md)**
> changes for better view of page

- lang/scala.md
Added Scala Language in ```lang``` folder
**[Signed commits](https://github.com/devstrons/heloworld/blob/master/CONTRIBUTING.md)**
```AnonymousGeek#9515```
> Adding Scala language

- LICENSE
- README.md
- Update copyright notices to 2022.
**[Signed commits](https://github.com/devstrons/heloworld/blob/master/CONTRIBUTING.md)**
`Panquesito7#3723`
> chore: update copyright notices to 2022
